from flask import Flask, jsonify
import os

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def home():
    # 1. Проверяваме какво има в environment
    env_keys = list(os.environ.keys())
    
    token = os.environ.get('eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJlMGNlOTZjOTEwYzRhNDU5Zjg5ZmJjN2QzNzk2MTI5OSIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiZTBjZTk2YzkxMGM0YTQ1OWY4OWZiYzdkMzc5NjEyOTkiLCJpYXQiOjE3NjUzODY0NTd9.f8e1x5sdp2vH_z1Nwpj0fJ7sKbDGN31SL8cMdpTrDXklLiqaI7vcLoYQsgBr3_zgZqvr1qqMfewNE8U3e0IJcN7yhXMk2aKPK9Ykec3DiivGIPL3Cow5t_kqZ-0sgAgqnYEEAi73YDhckDSpklcvKGLHri8w2sxFSOycIwwGiu1ca7Vbd4qfpnjvY3GRtIH6zsqWNuJMdXaBoCHkSrRsB7GAGGhLZyVhsivMFubykZrZBlrADRUlCX96nCk3Mnttm569zVE0vvzgPUz-UCOx_6yTDjpBLodqUbFj5oa35fDG5FzDqclk-ihe3QgkYOP4tBW-B_ZMqr4YWttRadcSo9p9aZk0st8sEfHo0KltR8iGbQ7-UBESc0TSVtAsROYN07CWd5TgIbxi_1gfT6bUUK5QuzIRE848g-Bsj6kKomPh3lHTBMu-0c4dkqIpM8gb7SzAQ4S-mG_JXZXHJ2lzpIfyCKWPdokXykRRsJ70q4-zb2ACKQdAsaoaJB7g_9FUQUfHEznasePpyKzVWCG8QA8j6NCVcqywFMlM_buwcj7OHYmdiaV6t1qudxHrFkgFJS1cBJ8TlQTGgqK5cUPpEiG1hnpM71DDW3pPH0EuObXV5YguF5pY_n_pilmTz0HDWNXioZoZkr2rkmvS98WSxaORIQaaCiaykm04V3oxarA', '')
    acc_id = os.environ.get('1807c98f-56c0-4021-a556-7815866eb07d', '')
    
    # Скриваме тайните, показваме само дали ги има и дължината им
    report = {
        "1_Diagnostics": "Running variable check...",
        "2_METAAPI_TOKEN_Status": "FOUND" if token else "MISSING",
        "3_METAAPI_TOKEN_Length": len(token),
        "4_ACCOUNT_ID_Status": "FOUND" if acc_id else "MISSING",
        "5_ACCOUNT_ID_Length": len(acc_id),
        "6_All_Available_Keys": [k for k in env_keys if not k.startswith('AWS')] # Показваме кои ключове изобщо съществуват
    }
    
    return jsonify(report)

if __name__ == '__main__':
    app.run()